//
//  SampleActivityCatalog.swift
//  坐标系
//
//  扩充活动种子：偏日常高频、好约、有吸引力的局（球类 / 吃喝 / 娱乐）。
//  ID 从 23 起；目录升级靠 catalogVersion。
//

import Foundation
import CoordinateModels

enum SampleActivityCatalog {
    private static func day(_ offset: Int, hour: Int, minute: Int = 0) -> Date {
        let cal = Calendar.current
        let base = cal.date(byAdding: .day, value: offset, to: .now) ?? .now
        return cal.date(bySettingHour: hour, minute: minute, second: 0, of: base) ?? base
    }

    private static func hours(_ h: Double) -> Date {
        .now.addingTimeInterval(3600 * h)
    }

    private static func id(_ n: Int) -> UUID { SampleData.activityID(n) }

    /// 约 40 场高频局，保证长列表分区有货
    static let extra: [Activity] = [
        // 运动
        Activity(id: id(23), title: "飞盘局：公园开团", category: .outdoorSports,
                 location: "杨浦 · 共青森林公园大草坪", date: day(1, hour: 16),
                 capacity: 14, joined: 11, hostName: "飞盘阿木",
                 summary: "规则会教，男女混搭。自备水杯，飞盘可借。",
                 fee: "免费", tags: ["飞盘", "户外", "新手"], distanceKM: 7.4,
                 participantNames: ["飞盘阿木", "Yuna", "Leo", "Coco"], latitude: 31.3180, longitude: 121.5480),
        Activity(id: id(24), title: "徐汇夜骑续摊局", category: .outdoorSports,
                 location: "徐汇 · 龙华地铁站 2 号口", date: hours(8),
                 capacity: 10, joined: 4, hostName: "阿凯",
                 summary: "约 10 公里滨江往返，配速能聊天。骑完可吃夜宵。",
                 fee: "免费（自备车）", tags: ["骑行", "夜骑"], distanceKM: 2.9,
                 participantNames: ["阿凯", "林夏"], latitude: 31.1755, longitude: 121.4560),
        Activity(id: id(25), title: "静安羽毛球晚场", category: .outdoorSports,
                 location: "静安 · 静安体育中心", date: day(0, hour: 20),
                 capacity: 8, joined: 7, hostName: "羽球阿南",
                 summary: "3.0 左右水平，场地已定 2 小时。缺人速来。",
                 fee: "AA 约 40／人", tags: ["羽毛球", "运动搭子"], distanceKM: 1.2,
                 participantNames: ["羽球阿南", "阿凯", "Yuna", "Noon", "Coco", "Leo", "林夏"],
                 latitude: 31.2290, longitude: 121.4450),
        Activity(id: id(26), title: "周末爬山：佘山轻松线", category: .outdoorSports,
                 location: "松江 · 西佘山园门口", date: day(6, hour: 9),
                 capacity: 16, joined: 9, hostName: "禾野",
                 summary: "约 8 公里，中午下山吃饭。不硬核，新手也能跟。",
                 fee: "门票自理", tags: ["爬山", "徒步", "周末"], distanceKM: 22.0,
                 participantNames: ["禾野", "阿禾", "林夏"], latitude: 31.0960, longitude: 121.1860),
        Activity(id: id(27), title: "篮球半场娱乐赛", category: .outdoorSports,
                 location: "浦东 · 源深球场", date: day(3, hour: 18, minute: 30),
                 capacity: 10, joined: 6, hostName: "Leo",
                 summary: "半场 5V5 轮换，水平休闲。自备球鞋。",
                 fee: "免费", tags: ["篮球", "周末"], distanceKM: 5.5,
                 participantNames: ["Leo", "阿凯", "Noon", "Yuna", "Coco", "小周"],
                 latitude: 31.2320, longitude: 121.5300),

        // 社交 / 轻松局
        Activity(id: id(28), title: "奶茶探店双人档", category: .interestSocial,
                 location: "静安 · 南京西路近陕西南路", date: day(0, hour: 15),
                 capacity: 6, joined: 3, hostName: "Mia",
                 summary: "两家排队店打卡，边喝边吐槽工作。来去自由。",
                 fee: "人均约 30（自费）", tags: ["探店", "奶茶", "聊天局"], distanceKM: 0.9,
                 participantNames: ["Mia", "林夏", "Coco"], latitude: 31.2245, longitude: 121.4500),
        Activity(id: id(29), title: "周五微醺小酌", category: .interestSocial,
                 location: "徐汇 · 衡山路酒吧街", date: day(2, hour: 20),
                 capacity: 8, joined: 5, hostName: "夜谈阿白",
                 summary: "一杯起步，不劝酒。聊聊近况，认识新朋友。",
                 fee: "自费点单", tags: ["聊天局", "微醺"], distanceKM: 2.5,
                 participantNames: ["夜谈阿白", "Mia", "小周", "Noon", "Coco"],
                 latitude: 31.2000, longitude: 121.4450),
        Activity(id: id(30), title: "轰趴做饭局", category: .interestSocial,
                 location: "长宁 · 轰趴馆（群内发）", date: day(4, hour: 15),
                 capacity: 10, joined: 6, hostName: "派对阿可",
                 summary: "一起买菜做饭 + 桌游 + K 歌。材料费 AA。",
                 fee: "人均约 100（含场）", tags: ["轰趴", "主题派对", "桌游"], distanceKM: 4.8,
                 participantNames: ["派对阿可", "Coco", "小周", "Mia", "Noon", "林夏"],
                 latitude: 31.2180, longitude: 121.4200),
        Activity(id: id(31), title: "热映大片拼票", category: .entertainment,
                 location: "长宁 · 龙之梦影城", date: day(5, hour: 19, minute: 20),
                 capacity: 8, joined: 4, hostName: "麦旋风",
                 summary: "看当周热映，座位连坐。散场可续摊。",
                 fee: "票价自理", tags: ["电影夜", "逛街"], distanceKM: 4.8,
                 participantNames: ["麦旋风", "林夏", "Coco", "小周"], latitude: 31.2180, longitude: 121.4160),

        // 美食
        Activity(id: id(32), title: "静安火锅局", category: .food,
                 location: "静安 · 南京西路火锅店（已订位）", date: day(1, hour: 18, minute: 30),
                 capacity: 8, joined: 6, hostName: "小周",
                 summary: "鸳鸯锅，忌口提前说。肉菜管够。",
                 fee: "人均 120–150", tags: ["火锅局", "晚饭"], distanceKM: 1.1,
                 participantNames: ["小周", "Mia", "Coco", "Noon", "阿禾", "林夏"],
                 latitude: 31.2260, longitude: 121.4480),
        Activity(id: id(33), title: "炸鸡啤酒周五夜", category: .food,
                 location: "徐汇 · 宜山路炸鸡店", date: day(0, hour: 19, minute: 30),
                 capacity: 8, joined: 4, hostName: "炸鸡阿梨",
                 summary: "炸鸡拼盘 + 啤酒。能喝就喝，不喝饮料也行。",
                 fee: "人均 70–90", tags: ["夜宵", "探店"], distanceKM: 3.2,
                 participantNames: ["炸鸡阿梨", "Mia", "Noon", "阿凯"], latitude: 31.1900, longitude: 121.4200),
        Activity(id: id(34), title: "周末早午餐拼桌", category: .food,
                 location: "黄浦 · 外滩附近 Brunch", date: day(6, hour: 11),
                 capacity: 7, joined: 3, hostName: "Brunch 阿可",
                 summary: "已订位，迟到超 15 分钟可能开吃。",
                 fee: "人均 100–130", tags: ["探店", "Brunch"], distanceKM: 3.4,
                 participantNames: ["Brunch 阿可", "小周", "Coco"], latitude: 31.2360, longitude: 121.4860),
        Activity(id: id(35), title: "自助海鲜畅吃", category: .food,
                 location: "浦东 · 世纪汇附近", date: day(3, hour: 18),
                 capacity: 8, joined: 5, hostName: "海鲜阿满",
                 summary: "晚餐场自助，集合后一起进。吃回本小队集合。",
                 fee: "人均约 198", tags: ["自助餐", "晚饭"], distanceKM: 7.0,
                 participantNames: ["海鲜阿满", "小周", "Mia", "Coco", "Noon"],
                 latitude: 31.2200, longitude: 121.5350),

        // 娱乐
        Activity(id: id(36), title: "剧本杀：本格推理", category: .entertainment,
                 location: "静安 · 剧本杀馆（群内发店名）", date: day(2, hour: 14),
                 capacity: 6, joined: 5, hostName: "推理阿哲",
                 summary: "6 人本格，新手友好；约 5 小时。",
                 fee: "馆费约 128／人", tags: ["剧本杀", "推理"], distanceKM: 1.5,
                 participantNames: ["推理阿哲", "Coco", "小周", "Noon", "骰子阿北"],
                 latitude: 31.2280, longitude: 121.4470),
        Activity(id: id(37), title: "Switch 聚会开黑", category: .entertainment,
                 location: "徐汇 · 客厅局（近交大）", date: hours(26),
                 capacity: 8, joined: 4, hostName: "主机阿狸",
                 summary: "马里奥派对 + 双人成行。自备手柄更好。",
                 fee: "零食 AA 约 25", tags: ["Switch 聚会", "电竞比赛"], distanceKM: 4.0,
                 participantNames: ["主机阿狸", "Leo", "Yuna", "Noon"], latitude: 31.2000, longitude: 121.4350),
        Activity(id: id(38), title: "桌游：德式轻松局", category: .entertainment,
                 location: "长宁 · 桌游咖啡", date: day(4, hour: 14),
                 capacity: 8, joined: 3, hostName: "骰子阿北",
                 summary: "派对游戏混搭，会教规则。适合新手。",
                 fee: "台费约 35／人", tags: ["桌游", "卡牌游戏"], distanceKM: 5.0,
                 participantNames: ["骰子阿北", "Coco", "小周"], latitude: 31.2200, longitude: 121.4150),
        Activity(id: id(39), title: "密室：恐怖馆拼队", category: .entertainment,
                 location: "黄浦 · 人民广场附近", date: day(5, hour: 15, minute: 30),
                 capacity: 6, joined: 2, hostName: "解密阿澄",
                 summary: "2 小时恐怖向，胆子小慎入。缺两人。",
                 fee: "约 150／人", tags: ["密室逃脱", "沉浸体验"], distanceKM: 2.6,
                 participantNames: ["解密阿澄", "阿凯"], latitude: 31.2330, longitude: 121.4750),

        // 城市玩乐
        Activity(id: id(40), title: "城隍庙小吃打卡", category: .cityExplore,
                 location: "黄浦 · 豫园商城正门", date: day(0, hour: 17),
                 capacity: 12, joined: 7, hostName: "老街阿成",
                 summary: "南翔馒头、糖炒栗子随便点，边吃边逛。",
                 fee: "餐食自费", tags: ["小吃", "夜市", "探店"], distanceKM: 3.8,
                 participantNames: ["老街阿成", "小周", "林夏", "Coco", "Noon", "Mia", "阿禾"],
                 latitude: 31.2270, longitude: 121.4920),
        Activity(id: id(41), title: "迪士尼轻松一日", category: .cityExplore,
                 location: "浦东 · 迪士尼地铁站集合", date: day(6, hour: 9),
                 capacity: 8, joined: 5, hostName: "周末阿行",
                 summary: "门票自备，园内自由组队。不硬排爆款项目。",
                 fee: "门票自理", tags: ["一日游", "周末"], distanceKM: 28.0,
                 participantNames: ["周末阿行", "Mia", "Coco", "小周", "林夏"],
                 latitude: 31.1440, longitude: 121.6570),
        Activity(id: id(42), title: "五角场逛街吃吃", category: .cityExplore,
                 location: "杨浦 · 五角场下沉广场", date: day(3, hour: 14),
                 capacity: 10, joined: 4, hostName: "逛街阿可",
                 summary: "逛街 + 探店 + 晚饭，不强制买买买。",
                 fee: "消费自理", tags: ["逛街", "探店"], distanceKM: 8.0,
                 participantNames: ["逛街阿可", "Mia", "林夏", "Coco"], latitude: 31.3000, longitude: 121.5150),
        Activity(id: id(43), title: "欢乐谷刺激项目局", category: .cityExplore,
                 location: "松江 · 欢乐谷正门", date: day(7, hour: 10),
                 capacity: 10, joined: 4, hostName: "过山车阿飞",
                 summary: "门票自备，专攻刺激项目。恐高慎入。",
                 fee: "门票自理", tags: ["一日游", "周末"], distanceKM: 26.0,
                 participantNames: ["过山车阿飞", "Leo", "阿凯", "Noon"], latitude: 31.0900, longitude: 121.2200),

        // 手工改成更大众的体验
        Activity(id: id(44), title: "烘焙饼干手作局", category: .handmade,
                 location: "徐汇 · 烘焙工作室", date: day(2, hour: 15),
                 capacity: 8, joined: 5, hostName: "甜品阿梨",
                 summary: "做一盒曲奇带走，材料全包。适合约会/朋友局。",
                 fee: "材料费 98", tags: ["烘焙", "手作 DIY"], distanceKM: 3.3,
                 participantNames: ["甜品阿梨", "Mia", "Coco", "林夏", "小周"],
                 latitude: 31.1950, longitude: 121.4400),
        Activity(id: id(45), title: "美甲体验拼团", category: .handmade,
                 location: "静安 · 美甲店（群内发）", date: day(4, hour: 14),
                 capacity: 4, joined: 2, hostName: "美甲小满",
                 summary: "简约款体验价，可结伴聊天等干。",
                 fee: "体验约 79", tags: ["手作 DIY"], distanceKM: 1.5,
                 participantNames: ["美甲小满", "Mia"], latitude: 31.2250, longitude: 121.4480),
        Activity(id: id(46), title: "市集淘货逛街局", category: .handmade,
                 location: "徐汇 · 滨江周末市集", date: day(6, hour: 12),
                 capacity: 10, joined: 6, hostName: "阿梨",
                 summary: "淘耳饰小物、吃小吃，16:00 咖啡集合晒战利品。",
                 fee: "免费入场", tags: ["市集手作", "逛街", "探店"], distanceKM: 3.5,
                 participantNames: ["阿梨", "Coco", "Mia", "林夏", "小周", "Noon"],
                 latitude: 31.1740, longitude: 121.4610),
        Activity(id: id(47), title: "出片打卡：外滩夜景", category: .cityExplore,
                 location: "黄浦 · 陈毅广场", date: day(1, hour: 19),
                 capacity: 8, joined: 4, hostName: "镜头阿川",
                 summary: "互帮拍照出片，手机也行。拍完可续摊。",
                 fee: "免费", tags: ["拍照", "夜游", "逛街"], distanceKM: 3.1,
                 participantNames: ["镜头阿川", "林夏", "Coco", "Mia"], latitude: 31.2380, longitude: 121.4870),

        // 学习 → 更实用/社交向
        Activity(id: id(48), title: "乒乓球晚训局", category: .outdoorSports,
                 location: "杨浦 · 创智天地球馆", date: day(2, hour: 19, minute: 30),
                 capacity: 8, joined: 4, hostName: "球馆阿南",
                 summary: "娱乐对拉，可教新手发球。球拍可租。",
                 fee: "AA 约 30／人", tags: ["乒乓球", "运动搭子"], distanceKM: 8.8,
                 participantNames: ["球馆阿南", "Leo", "Noon", "林夏"], latitude: 31.3040, longitude: 121.5140),
        Activity(id: id(49), title: "短视频跟拍局", category: .learning,
                 location: "静安 · 南京西路集合", date: day(5, hour: 15),
                 capacity: 6, joined: 3, hostName: "剪辑阿南",
                 summary: "一起拍一条周末 vlog，互帮出镜。手机即可。",
                 fee: "免费", tags: ["剪辑学习", "拍照"], distanceKM: 1.3,
                 participantNames: ["剪辑阿南", "林夏", "Coco"], latitude: 31.2250, longitude: 121.4460),
        Activity(id: id(50), title: "网球娱乐对打", category: .outdoorSports,
                 location: "徐汇 · 上海体育场网球场", date: day(3, hour: 19),
                 capacity: 4, joined: 2, hostName: "Leo",
                 summary: "场地已订，可借拍。会打底线就行。",
                 fee: "AA 约 55／人", tags: ["网球", "入门"], distanceKM: 4.1,
                 participantNames: ["Leo", "Yuna"], latitude: 31.1835, longitude: 121.4395),
        Activity(id: id(51), title: "游泳夜场拼伴", category: .outdoorSports,
                 location: "静安 · 静安游泳馆", date: day(1, hour: 20),
                 capacity: 8, joined: 3, hostName: "泳队阿青",
                 summary: "自由游 1 小时，互有个伴。会换气即可。",
                 fee: "门票约 40", tags: ["游泳", "运动搭子"], distanceKM: 1.6,
                 participantNames: ["泳队阿青", "Yuna", "林夏"], latitude: 31.2265, longitude: 121.4510),

        // 补今晚 / 附近 / 周末密度
        Activity(id: id(52), title: "午后飞盘混搭", category: .outdoorSports,
                 location: "静安 · 静安公园", date: day(0, hour: 13, minute: 30),
                 capacity: 12, joined: 5, hostName: "飞盘阿木",
                 summary: "午后一小时，路过也能加入。",
                 fee: "免费", tags: ["飞盘", "轻松"], distanceKM: 0.7,
                 participantNames: ["飞盘阿木", "阿禾"], latitude: 31.2230, longitude: 121.4465),
        Activity(id: id(53), title: "今晚串串局", category: .food,
                 location: "黄浦 · 老西门串串店", date: day(0, hour: 20, minute: 30),
                 capacity: 8, joined: 4, hostName: "串串阿木",
                 summary: "冒菜串串，微辣起步。吃完可续摊。",
                 fee: "人均 70–90", tags: ["串串", "夜宵", "火锅局"], distanceKM: 2.4,
                 participantNames: ["串串阿木", "Mia", "小周", "Noon"], latitude: 31.2200, longitude: 121.4900),
        Activity(id: id(54), title: "周六早晨骑行拉练", category: .outdoorSports,
                 location: "浦东 · 陆家嘴滨江", date: day(6, hour: 8),
                 capacity: 16, joined: 7, hostName: "阿凯",
                 summary: "约 20 公里轻松骑，骑完早饭。自备车。",
                 fee: "免费", tags: ["骑行", "周末"], distanceKM: 6.5,
                 participantNames: ["阿凯", "林夏", "Leo", "Noon", "Yuna", "Coco", "小周"],
                 latitude: 31.2365, longitude: 121.5060),
        Activity(id: id(55), title: "周日羽毛球畅打", category: .outdoorSports,
                 location: "徐汇 · 体育中心球馆", date: day(7, hour: 10),
                 capacity: 8, joined: 4, hostName: "羽球阿南",
                 summary: "上午两小时混打，水平 2.5–3.5。",
                 fee: "AA 约 40／人", tags: ["羽毛球", "周末"], distanceKM: 3.1,
                 participantNames: ["羽球阿南", "阿凯", "Yuna", "林夏"], latitude: 31.1850, longitude: 121.4400),
        Activity(id: id(56), title: "羽毛球午间快打", category: .outdoorSports,
                 location: "黄浦 · 近外滩球馆", date: day(1, hour: 12, minute: 10),
                 capacity: 6, joined: 5, hostName: "羽球阿南",
                 summary: "午休 50 分钟快打，更衣室有寄存。",
                 fee: "AA 约 30／人", tags: ["羽毛球"], distanceKM: 2.8,
                 participantNames: ["羽球阿南", "阿凯", "Leo", "Yuna", "Noon"],
                 latitude: 31.2350, longitude: 121.4850),
        Activity(id: id(57), title: "火锅续摊第二趴", category: .food,
                 location: "静安 · 另一家火锅（群内发）", date: day(2, hour: 19),
                 capacity: 8, joined: 3, hostName: "小周",
                 summary: "想吃辣的来，微辣/中辣可选。",
                 fee: "人均 110–140", tags: ["火锅局", "晚饭"], distanceKM: 1.2,
                 participantNames: ["小周", "Mia", "Coco"], latitude: 31.2240, longitude: 121.4490),
        Activity(id: id(58), title: "桌游夜：狼人杀进阶", category: .entertainment,
                 location: "浦东 · 桌游吧", date: day(1, hour: 19, minute: 45),
                 capacity: 12, joined: 6, hostName: "骰子阿北",
                 summary: "会基本规则即可。今晚打满 3 局。",
                 fee: "台费约 40／人", tags: ["桌游", "狼人杀"], distanceKM: 7.2,
                 participantNames: ["骰子阿北", "Coco", "小周", "Noon", "Mia", "林夏"],
                 latitude: 31.2300, longitude: 121.5400),
        Activity(id: id(59), title: "夜跑间歇入门", category: .outdoorSports,
                 location: "徐汇 · 上海体育场外圈", date: day(2, hour: 19, minute: 45),
                 capacity: 14, joined: 6, hostName: "Noon",
                 summary: "热身 + 间歇 + 拉伸，配速可分组。",
                 fee: "免费", tags: ["跑步", "夜跑"], distanceKM: 4.2,
                 participantNames: ["Noon", "Leo", "Yuna"], latitude: 31.1840, longitude: 121.4400),
        Activity(id: id(60), title: "KTV 周末麦霸局", category: .entertainment,
                 location: "徐汇 · 漕溪路 KTV", date: day(6, hour: 15),
                 capacity: 10, joined: 5, hostName: "麦旋风",
                 summary: "下午场中包 3 小时，歌单不限。",
                 fee: "AA 约 50／人", tags: ["KTV", "唱歌"], distanceKM: 4.0,
                 participantNames: ["麦旋风", "Coco", "Mia", "小周", "林夏"], latitude: 31.1900, longitude: 121.4350),
        Activity(id: id(61), title: "探店：网红汉堡店", category: .food,
                 location: "徐汇 · 武康路附近", date: day(4, hour: 12),
                 capacity: 6, joined: 3, hostName: "探店阿梨",
                 summary: "排队店拼桌，拍完照开吃。人均可控。",
                 fee: "人均 60–80", tags: ["探店", "午饭"], distanceKM: 2.5,
                 participantNames: ["探店阿梨", "Mia", "林夏"], latitude: 31.2060, longitude: 121.4410),
        Activity(id: id(62), title: "免费博物馆半日逛", category: .cityExplore,
                 location: "黄浦 · 上海历史博物馆", date: day(3, hour: 13),
                 capacity: 12, joined: 5, hostName: "逛街阿可",
                 summary: "预约票各自解决，馆内自由看，出口奶茶复盘。",
                 fee: "免费", tags: ["看展", "逛街", "周末"], distanceKM: 2.9,
                 participantNames: ["逛街阿可", "Mia", "林夏", "Coco", "小周"],
                 latitude: 31.2240, longitude: 121.4780)
    ]
}
